[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
same-file = "1"
memmap = "0.7"
walkdir = "2"
glob = "0.3"