[workspace]

members = [
    "algorithms",
    "concurrency",
    "clap_basic",
    "ansi_terminal",
    "sqlite",
    "dbpostgres",
    "dateandtime",
    "encoding",
    "error_handling",
    "filesystem",
    "systems",
    "science",
    "text",
    "web",
]